<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <LangVersion>10.0</LangVersion>
    <TargetFramework>net472</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="GitHubActionsTestLogger" Version="3.0.5" />
    <PackageReference Include="JetBrains.ReSharper.SDK.Tests" Version="$(SdkVersion)" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="6.2.0" />
    <PackageReference Update="DiffEngine" Version="20.0.0-beta.33" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ReSharperPlugin.Verify\ReSharperPlugin.Verify.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="test/**/*" />
    <None Include="test/**/*" />
  </ItemGroup>

</Project>
